### ISSUE TITLE
Suggestion: Include adding Icons to regular menu entries

### ISSUE THREAD

**Issue by Jacksaur** [vandalsoul/grub-tweaks#4]
I understand that the Submenu section pretty much already explains how to do this, but the format for the standard menu entries is a little different.
There are multiple guides across the internet for doing this, but the majority are low effort and just tell users to edit GRUB.cfg directly, despite the giant "DO NOT EDIT THIS FILE" header it has.

A small section for adding (or fixing, many Distro variants just show the icon for their parent Distro) icons for regular menu entries could be really helpful for new users, and make it more likely for them to stumble upon this page in general while searching.

**Comment by Jacksaur** [comment]
Certainly! I'm still pretty new to Github but I'll write up a section myself and look into how to contribute properly.

**Comment by vandalsoul** [comment]
@Jacksaur 
Oh cool, that'll be really helpful 😇

**Comment by Jacksaur** [comment]
Heh, well it's been a great learning experience so far. Found that GRUB Customizer messes with the grub.d files and makes them unusable with this guide, then managed to break my entire GRUB install whilst trying to revert it and fixed it again. So that at least gives me another section to write!

I'm unaware of the general etiquette of all this: Would you prefer I submit one Pull Request per section, or multiple all in one?

**Comment by vandalsoul** [comment]
@Jacksaur 
>Heh, well it's been a great learning experience so far. Found that GRUB Customizer messes with the grub.d files and makes them unusable with this guide, then managed to break my entire GRUB install whilst trying to revert it and found how to fix it again. So that at least gives me another section to write!
 
Hah yeah happens a lot, I personally don't use Grub customizer that much. You should use a VM, you know for testing stuff ( ie if you aren't using one already )

>Would you prefer I submit one Pull Request per section, or multiple all in one?

You can do it either way you want, personally I would suggest to apply all the changes then submitting a pull request 👍

**Comment by Jacksaur** [comment]
Welp, I gave it a try, and unfortunately failed. I assumed it would be as simple as the Submenu section, just add a --class line with the name of the Distro icon you want to use. But it seems Distro maintainers *massively* [overcomplicate these lines](https://i.imgur.com/lOpTIeX.png) with [numerous variables and functions to dig back through](https://i.imgur.com/dMlgcri.png). I couldn't find a way to reliably change the --class entry other than just making an entirely custom menu entry: which I feel is out of scope for a "Tweak". Let alone the fact that the process will be different depending on how each Distro maintainer messes with their default GRUB configuration.
I'll keep looking around and maybe sometime I'll find an easy method I can contribute. But as usual GRUB is sorely lacking in documentation for these things, and Canonical's tampering here certainly doesn't help.

Regardless though, I did at least open a PR for a section on fully reinstalling GRUB like I had to earlier when I first broke my install. Should be useful for anyone who ignores the warnings to back up their files.

**Comment by vandalsoul** [comment]
@Jacksaur Well at least you learnt some new stuff right

> I couldn't find a way to reliably change the --class entry other than just making an entirely custom menu entry: which I feel is out of scope for a "Tweak". Let alone the fact that the process will be different depending on how each Distro maintainer messes with their default GRUB configuration.

maybe this can be made into a tweak script in the future, we can use a .py DB to store the differences of each distro and change grub file entries accordingly, I will give it a go when I can 👍👍
